#!/usr/bin/env bash
#display contents of the file /etc/passwd
#display username, user id and Home directory path for the user

FILENAME="/etc/passwd"
content=$(cat /etc/passwd)
while read -r line; do
username=$(echo $line | awk -F: '{print $1}')
userid=$(echo $line | awk -F: '{print $3}')
homedir=$(echo $line | awk -F: '{print $6}')
	echo "Username: $username"
	echo "User ID: $userid"
	echo "Home Directory: $homedir"
	echo ""
done <<< "$content"
