#!/usr/bin/env bash
#display content of the file /etc/passwd using LOOP+IFS

while IFS=: read -r c1 c2 c3 c4 c5 c6 c7
do
	echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. $f3's place is protected by the passcode $f2, more info about the user here: $f5"
done < /etc/passwd
