#!/usr/bin/env bash
#groups visitors IP and HTTP status code and displays this data
if [ ! -f "apache-access.log" ]; then
	echo "Error: File apache-access.log does not exist."
	exit 
fi
awk '{print $1,$9}' apache-acess.log | sort | uniq -c | sort -nr
