#!/usr/bin/env bash
#dislays content of current directory in a list format where only the part of the name after first dash is displayed

files=$(ls -1 | grep -v '^\.')
for file in $files;do
name=${file#*-}
echo "$name"
done
