#!/usr/bin/env bash
#dislays content of current directory in a list format where only the part of the name after first dash is displayed
list=$(ls)
for i in $list; do
	echo "$i" | cut -d '-' -f2
done
