#!/usr/bin/env bash
#stops 4-to_infinity_and_beyond process
#find process ID of 4-to_infinity_and_beyond
pid=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

#kill the 4-to_infinity_and_beyond process

if [ -n "$pid" ]
then
	kill -l5 "$pid"
fi

