#!/usr/bin/env bash
#stops 4-to_infinity_and_beyond process
#find process ID of 4-to_infinity_and_beyond
id=$(pgrep "4-to_infinity_and_beyond")

#kill the 4-to_infinity_and_beyond process

if [ -z "$id" ]; then
	echo "4-to_infinity-and_beyond"
else
	kill "$id"
fi

